#!/bin/bash
#quick wrapper to use the right libs for this project 
perl -I ./lib/ \
-I "./foreign/Moo-GenericRole/lib/" \
-I "./foreign/Moo-Task-FileDB/lib/" \
-I "./foreign/SubSystem-TagForSubject/lib/" \
"$@"
 
