#!/bin/bash
#quick wrapper to use the right libs for this project 
prove -I ./lib/ \
-I "./foreign/Moo-GenericRole/lib/" \
-I "./foreign/Moo-Task-FileDB/lib/" \
-I "./foreign/Moo-Task-SubjectTagDB/lib/" \
"$@"
 
